INCLUDE(FindPackageHandleStandardArgs)

FIND_LIBRARY(GENICAM_LIBRARY_3_0 GenApi_gcc_v3_0_Basler_pylon_v5_0
  /opt/pylon5/lib
)

SET(GENICAM_LIBRARY ${GENICAM_LIBRARY_3_0})

FIND_PATH(GENICAM_INCLUDE_PATH GenICamVersion.h
  "$ENV{GENICAM_INCLUDE_PATH}"
  /opt/pylon5/include/
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(GENICAM DEFAULT_MSG
  GENICAM_INCLUDE_PATH
  GENICAM_LIBRARY)

